#########################################################
# Specify the name of the target executable

TARGETS:=onlyFatimaTrace10Bit

#########################################################
# Include common Makefile

include ../makefile_common.mk
