#########################################################
# Specify the name of the target executable

TARGETS:=onlyFatimaTrace8Bit

#########################################################
# Include common Makefile

include ../makefile_common.mk
